"use client";

import Link from "next/link";
import PublicHeader from "@/components/PublicHeader";
import PublicFooter from "@/components/PublicFooter";
import DownloadPDFButton from "@/components/DownloadPDFButton";

interface ChecklistClientProps {
  locale: "en" | "pt";
}

const t = {
  en: {
    title: "Visitor Log Audit Checklist",
    subtitle:
      "10 things an inspector looks for in your visitor log – regardless of industry.",
    inspectorLabel: "What an inspector checks:",
    fixLabel: "Quick fix:",
    cta: "Want a digital solution that covers all of this automatically?",
    ctaLink: "Try SiteSafe free for 14 days.",
    printFooter: "Generated by SiteSafe – sitesafe.thesift.space",
    items: [
      {
        point: "Full legal name, every time",
        inspector: "Auditors need to confirm exactly who was on site. Initials or nicknames won't hold up.",
        fix: "Make the full name field required before submission.",
      },
      {
        point: "Company or trade affiliation",
        inspector: "Tells the inspector why the visitor was there and who was responsible for them.",
        fix: "Add a mandatory company field and pre-fill it for known contractors.",
      },
      {
        point: "Host name (who they came to see)",
        inspector: "During an emergency or audit, you need to know which employee or department authorised the visit.",
        fix: "Provide a dropdown of current hosts so the correct person is always selected.",
      },
      {
        point: "Precise arrival time (down to the minute)",
        inspector: "Vague entries like 'morning' are useless. Inspectors need a timestamp.",
        fix: "Automatically stamp the arrival time on sign-in.",
      },
      {
        point: "Departure time or confirmation they left",
        inspector: "You don't want to be searching for someone who already left. Missing departure times are a red flag.",
        fix: "Offer a one-tap sign-out button and allow hosts to sign people out remotely.",
      },
      {
        point: "Acknowledged safety or policy briefing",
        inspector: "Without proof a visitor was informed of hazards, you're exposed. A signature or checkbox is mandatory.",
        fix: "Make the acknowledgment a required step before the visitor can proceed.",
      },
      {
        point: "Legible handwriting",
        inspector: "If you can't read it, the inspector can't either. Scribbled entries are a liability.",
        fix: "Use a digital form to eliminate handwriting entirely.",
      },
      {
        point: "No blank lines between entries",
        inspector: "Gaps invite fraudulent additions after the fact.",
        fix: "Use a system that logs every entry sequentially and prevents after-the-fact inserts.",
      },
      {
        point: "Consistent format across all pages and sites",
        inspector: "If you have multiple locations with different log styles, comparing records is impossible.",
        fix: "Standardise your check-in process across every site with the same digital tool.",
      },
      {
        point: "Secure, backed-up storage",
        inspector: "A damp clipboard or a drawer full of loose sheets won't survive an audit request.",
        fix: "Store visitor records in the cloud with encrypted access and automatic backups.",
      },
    ],
  },
  pt: {
    title: "Lista de Verificação de Auditoria de Registro de Visitantes",
    subtitle:
      "10 itens que um inspetor procura no seu registro de visitantes — independentemente da indústria.",
    inspectorLabel: "O que um inspetor verifica:",
    fixLabel: "Correção rápida:",
    cta: "Quer uma solução digital que cubra tudo isso automaticamente?",
    ctaLink: "Experimente a SiteSafe grátis por 14 dias.",
    printFooter: "Gerado por SiteSafe – sitesafe.thesift.space",
    items: [
      {
        point: "Nome legal completo, sempre",
        inspector: "Auditores precisam confirmar exatamente quem estava no local. Iniciais ou apelidos não valem.",
        fix: "Torne o campo de nome completo obrigatório antes do envio.",
      },
      {
        point: "Empresa ou afiliação profissional",
        inspector: "Diz ao inspetor por que o visitante estava lá e quem era responsável por ele.",
        fix: "Adicione um campo de empresa obrigatório e pré-preencha para contratados conhecidos.",
      },
      {
        point: "Nome do anfitrião (quem veio ver)",
        inspector: "Durante uma emergência ou auditoria, você precisa saber qual funcionário ou departamento autorizou a visita.",
        fix: "Forneça um dropdown de anfitriões atuais para que a pessoa correta seja sempre selecionada.",
      },
      {
        point: "Horário de chegada preciso (até o minuto)",
        inspector: "Entradas vagas como 'de manhã' são inúteis. Inspetores precisam de um timestamp.",
        fix: "Registre automaticamente o horário de chegada no check-in.",
      },
      {
        point: "Horário de saída ou confirmação de que saiu",
        inspector: "Você não quer procurar alguém que já saiu. Horários de saída ausentes são um sinal de alerta.",
        fix: "Ofereça um botão de saída com um toque e permita que anfitriões registrem saídas remotamente.",
      },
      {
        point: "Reconhecimento do briefing de segurança ou política",
        inspector: "Sem prova de que o visitante foi informado sobre riscos, você está exposto. Uma assinatura ou checkbox é obrigatória.",
        fix: "Torne o reconhecimento uma etapa obrigatória antes que o visitante possa prosseguir.",
      },
      {
        point: "Letra legível",
        inspector: "Se você não consegue ler, o inspetor também não. Entradas rabiscadas são um risco.",
        fix: "Use um formulário digital para eliminar a escrita à mão completamente.",
      },
      {
        point: "Sem linhas em branco entre entradas",
        inspector: "Lacunas convidam adições fraudulentas posteriormente.",
        fix: "Use um sistema que registre cada entrada sequencialmente e impeça inserções após o fato.",
      },
      {
        point: "Formato consistente em todas as páginas e locais",
        inspector: "Se você tem múltiplas unidades com diferentes estilos de registro, comparar registros é impossível.",
        fix: "Padronize seu processo de check-in em todos os locais com a mesma ferramenta digital.",
      },
      {
        point: "Armazenamento seguro e com backup",
        inspector: "Uma prancheta molhada ou uma gaveta cheia de folhas soltas não sobreviverá a uma solicitação de auditoria.",
        fix: "Armazene registros de visitantes na nuvem com acesso criptografado e backups automáticos.",
      },
    ],
  },
};

export default function ChecklistClient({ locale }: ChecklistClientProps) {
  const copy = t[locale];

  return (
    <div className="min-h-screen bg-[#0a0f1c] text-slate-200">
      <PublicHeader locale={locale} narrow />

      <main className="py-12 px-4">
        <div className="max-w-2xl mx-auto bg-white rounded-xl shadow-sm p-8 print:shadow-none print:p-0">
          <div className="flex items-center justify-between mb-4 print:hidden">
            <h1 className="text-2xl font-bold text-slate-800">{copy.title}</h1>
            <DownloadPDFButton />
          </div>
          <p className="text-sm text-slate-500 mb-6 print:text-xs">
            {copy.subtitle}
          </p>

          <ol className="space-y-6 print:space-y-4">
            {copy.items.map((item, i) => (
              <li key={i} className="border-b border-slate-100 pb-4 last:border-0">
                <h2 className="text-base font-semibold text-slate-800 print:text-sm">
                  {i + 1}. {item.point}
                </h2>
                <p className="text-sm text-slate-600 mt-1 print:text-xs">
                  <strong className="text-slate-700">{copy.inspectorLabel}</strong> {item.inspector}
                </p>
                <p className="text-sm text-slate-600 mt-0.5 print:text-xs">
                  <strong className="text-slate-700">{copy.fixLabel}</strong> {item.fix}
                </p>
              </li>
            ))}
          </ol>

          <p className="text-sm text-slate-400 mt-8 border-t pt-6 print:hidden">
            {copy.cta}{" "}
            <Link href="/signup" className="text-sky-600 underline">
              {copy.ctaLink}
            </Link>
          </p>

          <div className="hidden print:block text-xs text-slate-400 mt-6 border-t pt-4">
            {copy.printFooter}
          </div>
        </div>
      </main>
    </div>
  );
}