// app/checklist/page.tsx
export default function ChecklistPage() {
  const items = [
    "Full name of every visitor (no nicknames, no initials)",
    "Company or trade the visitor represents",
    "Host name – who the visitor came to see",
    "Date and time of arrival (accurate to the minute)",
    "Date and time of departure, or confirmation they left",
    "A signed or acknowledged safety / policy briefing",
    "Legible handwriting – if you can’t read it, an inspector can’t either",
    "No blank lines between entries (they invite fraudulent additions)",
    "Consistent format across all pages and all sites",
    "Secure storage – not a damp clipboard that gets thrown in a truck",
  ];

  return (
    <div className="min-h-screen py-12 px-4 print:py-4 print:px-2">
      <div className="max-w-2xl mx-auto bg-white rounded-xl shadow-sm p-8 print:shadow-none print:p-0">
        <h1 className="text-2xl font-bold text-slate-800 mb-2 print:text-xl">
          Visitor Log Audit Checklist
        </h1>
        <p className="text-sm text-slate-500 mb-6 print:text-xs">
          10 things an inspector looks for in your visitor log – regardless of
          industry.
        </p>
        <ol className="space-y-3 text-slate-700 print:text-sm">
          {items.map((item, i) => (
            <li key={i} className="flex gap-3">
              <span className="font-bold text-sky-600">{i + 1}.</span>
              <span>{item}</span>
            </li>
          ))}
        </ol>
        <p className="text-sm text-slate-400 mt-8 print:hidden">
          Want a digital solution that covers all of this automatically?{" "}
          <a href="/signup" className="text-sky-600 underline">
            Try SiteSafe free for 14 days.
          </a>
        </p>
        <div className="hidden print:block text-xs text-slate-400 mt-6 border-t pt-4">
          Generated by SiteSafe – sitesafe.thesift.space
        </div>
      </div>
    </div>
  );
}